name: Review Hook

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        name: Add Approved label
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{github.event.pull_request.number}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["${{github.event.review.user.login}} Approved"]
            })
      - name: Dump GitHub event
        env:
          GITHUB_PR_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: |
          echo "$GITHUB_PR_CONTEXT"
      - uses: actions/github-script@v6
        name: Add Already Approved Label
        env:
          GITHUB_PR_CONTEXT: ${{ toJson(github.event.pull_request) }}
        with:
          script: |
            const labels = context.payload.pull_request.labels
            let cnt = 0
            for (const label of labels) {
              if ("{label.name}".include(" Approved")) {
                cnt++
              }
            }
            if (cnt > 1) {
              github.rest.issues.addLabels({
                issue_number: ${{github.event.pull_request.number}},
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["ALREADY REVIEWED"]
              })
            }
#            github.rest.issues.addLabels({
#              issue_number: ${{github.event.pull_request.number}},
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              labels: ["${{github.event.review.user.login}} Approved"]
#            })


# https://stackoverflow.com/questions/68459601/can-we-add-labels-to-a-pull-request-while-creation-using-rest-api