name: Review Hook

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Dump GitHub event
        env:
          GITHUB_REVIEW_CONTEXT: ${{ toJson(github.event.review) }}
          GITHUB_PR_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: |
          echo "$GITHUB_REVIEW_CONTEXT"
          echo "$GITHUB_PR_CONTEXT"
          echo github.event.review.user.name
          echo context.repo.owner
          echo context.repo.repo
#      - uses: actions/github-script@v6
#        with:
#          script: |
#            github.rest.issues.addLabels({
#              issue_number: github.event.pull_request.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              labels: [github.event.review.user.name + " Approved"]
#            })


# https://stackoverflow.com/questions/68459601/can-we-add-labels-to-a-pull-request-while-creation-using-rest-api